colors:
  0:
  - 135
  - 255
  - 61
  - 51
  1:
  - 36
  - 155
  - 200
  - 51
  2:
  - 85
  - 0
  - 255
  - 46
  3:
  - 178
  - 255
  - 206
  - 74
  4:
  - 255
  - 255
  - 255
  - 50
  5:
  - 0
  - 170
  - 255
  - 50
  6:
  - 36
  - 155
  - 200
  - 50
  7:
  - 25
  - 255
  - 221
  - 50
  8:
  - 139
  - 255
  - 251
  - 50
  9:
  - 85
  - 255
  - 255
  - 50
  10:
  - 36
  - 155
  - 200
  - 50
  11:
  - 255
  - 0
  - 0
  - 50
  12:
  - 36
  - 155
  - 200
  - 50
  13:
  - 85
  - 0
  - 255
  - 50
default_cls: 0
names:
  0: '0'
  1: '1'
  2: '2'
  3: '3'
  4: '4'
  5: '5'
  6: '6'
  7: '7'
  8: '8'
  9: '9'
  10: '10'
  11: '11'
  12: '12'
  13: '13'
save_path: temp_folder
background_image: ''
background_opacity: 65
class_styles:
  0:
    border:
    - 93
    - 233
    - 255
    - 255
    border_width: 1
    fill:
    - 135
    - 255
    - 61
    - 51
    handle:
    - 255
    - 0
    - 0
    - 255
    handle_size: 6
    text:
    - 255
    - 37
    - 153
    - 255
    text_size: 20
    text_position: outside_top_left
  1:
    border:
    - 36
    - 155
    - 200
    - 230
    border_width: 1
    fill:
    - 36
    - 155
    - 200
    - 51
    handle:
    - 238
    - 68
    - 75
    - 230
    handle_size: 6
    text:
    - 36
    - 155
    - 200
    - 255
    text_size: 15
    text_position: outside_top_left
  2:
    border:
    - 85
    - 0
    - 255
    - 89
    border_width: 2
    fill:
    - 85
    - 0
    - 255
    - 46
    handle:
    - 137
    - 238
    - 183
    - 230
    handle_size: 8
    text:
    - 85
    - 0
    - 255
    - 255
    text_size: 20
    text_position: outside_top_left
  3:
    border:
    - 0
    - 0
    - 0
    - 191
    border_width: 2
    fill:
    - 178
    - 255
    - 206
    - 74
    handle:
    - 238
    - 68
    - 75
    - 178
    handle_size: 8
    text:
    - 255
    - 0
    - 0
    - 153
    text_size: 20
    text_position: outside_top_left
  4:
    border:
    - 255
    - 255
    - 255
    - 230
    border_width: 2
    fill:
    - 255
    - 255
    - 255
    - 50
    handle:
    - 238
    - 68
    - 75
    - 230
    handle_size: 8
    text:
    - 255
    - 255
    - 255
    - 255
    text_size: 20
    text_position: outside_top_left
  5:
    border:
    - 0
    - 170
    - 255
    - 230
    border_width: 2
    fill:
    - 0
    - 170
    - 255
    - 50
    handle:
    - 238
    - 68
    - 75
    - 230
    handle_size: 8
    text:
    - 0
    - 170
    - 255
    - 255
    text_size: 20
    text_position: outside_top_left
  6:
    border:
    - 36
    - 155
    - 200
    - 230
    border_width: 2
    fill:
    - 36
    - 155
    - 200
    - 50
    handle:
    - 238
    - 68
    - 75
    - 230
    handle_size: 8
    text:
    - 36
    - 155
    - 200
    - 255
    text_size: 20
    text_position: outside_top_left
  7:
    border:
    - 25
    - 255
    - 221
    - 230
    border_width: 2
    fill:
    - 25
    - 255
    - 221
    - 50
    handle:
    - 238
    - 68
    - 75
    - 230
    handle_size: 8
    text:
    - 25
    - 255
    - 221
    - 255
    text_size: 20
    text_position: outside_top_left
  8:
    border:
    - 139
    - 255
    - 251
    - 230
    border_width: 2
    fill:
    - 139
    - 255
    - 251
    - 50
    handle:
    - 238
    - 68
    - 75
    - 230
    handle_size: 8
    text:
    - 139
    - 255
    - 251
    - 255
    text_size: 20
    text_position: outside_top_left
  9:
    border:
    - 85
    - 255
    - 255
    - 230
    border_width: 2
    fill:
    - 85
    - 255
    - 255
    - 50
    handle:
    - 238
    - 68
    - 75
    - 230
    handle_size: 8
    text:
    - 85
    - 255
    - 255
    - 255
    text_size: 20
    text_position: outside_top_left
  10:
    border:
    - 36
    - 155
    - 200
    - 230
    border_width: 2
    fill:
    - 36
    - 155
    - 200
    - 50
    handle:
    - 238
    - 68
    - 75
    - 230
    handle_size: 8
    text:
    - 36
    - 155
    - 200
    - 255
    text_size: 20
    text_position: outside_top_left
  11:
    border:
    - 255
    - 0
    - 0
    - 230
    border_width: 2
    fill:
    - 255
    - 0
    - 0
    - 50
    handle:
    - 238
    - 68
    - 75
    - 230
    handle_size: 8
    text:
    - 255
    - 0
    - 0
    - 255
    text_size: 20
    text_position: outside_top_left
  12:
    border:
    - 36
    - 155
    - 200
    - 230
    border_width: 2
    fill:
    - 36
    - 155
    - 200
    - 50
    handle:
    - 238
    - 68
    - 75
    - 230
    handle_size: 8
    text:
    - 36
    - 155
    - 200
    - 255
    text_size: 20
    text_position: outside_top_left
  13:
    border:
    - 85
    - 0
    - 255
    - 230
    border_width: 2
    fill:
    - 85
    - 0
    - 255
    - 50
    handle:
    - 238
    - 68
    - 75
    - 230
    handle_size: 8
    text:
    - 85
    - 0
    - 255
    - 255
    text_size: 20
    text_position: outside_top_left
detection_confidence: 50
thumbnail_size: 74
shortcuts:
  previous_image: Z
  next_image: X
  detect: C
  delete_box: Delete
  zoom_in: '='
  zoom_out: '-'
  reset_view: '0'
  save_labels: Ctrl+S
  insert_segment_vertex: I
wheel_pan_enabled: false
wheel_zoom_enabled: true
annotation_task: detect
kpt_shape:
- 17
- 3
keypoint_names:
- 鼻子
- 左眼
- 右眼
- 左耳
- 右耳
- 左肩
- 右肩
- 左肘
- 右肘
- 左腕
- 右腕
- 左髋
- 右髋
- 左膝
- 右膝
- 左踝
- 右踝
kpt_skeleton:
- - 5
  - 6
- - 5
  - 7
- - 7
  - 9
- - 6
  - 8
- - 8
  - 10
- - 5
  - 11
- - 6
  - 12
- - 11
  - 12
- - 11
  - 13
- - 13
  - 15
- - 12
  - 14
- - 14
  - 16
- - 0
  - 1
- - 0
  - 2
- - 1
  - 3
- - 2
  - 4
